const nodemailer = require('nodemailer');
const supabase = require('../config/supabase');

const hasEmailConfig = Boolean(process.env.EMAIL_USER && process.env.EMAIL_PASS);

const transporter = hasEmailConfig
  ? nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      }
    })
  : null;

const emailStyles = `
  body { margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }
  .email-wrapper { background: linear-gradient(135deg, #e8f5e9 0%, #f1f8e9 100%); padding: 40px 20px; }
  .email-container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 8px 32px rgba(76, 175, 80, 0.1); }
  .header { background: linear-gradient(135deg, #66bb6a 0%, #81c784 100%); padding: 40px 30px; text-align: center; }
  .logo-section { margin-bottom: 15px; }
  .logo-img { height: 60px; margin-bottom: 10px; }
  .tagline { color: #e8f5e9; font-size: 14px; font-style: italic; margin: 8px 0 0 0; }
  .content { padding: 32px; color: #1f2937; }
  .title { margin: 0 0 12px 0; font-size: 24px; color: #2e7d32; }
  .message { margin: 0 0 20px 0; line-height: 1.7; color: #4b5563; }
  .panel { background: #f8faf7; border: 1px solid #dbe7d7; border-radius: 14px; padding: 20px; margin: 18px 0; }
  .panel h3 { margin: 0 0 12px 0; color: #2d5f3f; }
  .pill { display: inline-block; padding: 6px 12px; border-radius: 999px; background: #e8f4ea; color: #2d5f3f; margin: 4px 8px 4px 0; font-size: 13px; }
  .footer { background: #f5f5f5; padding: 30px; text-align: center; color: #757575; font-size: 13px; }
  .footer-links { margin: 15px 0; }
  .footer-link { color: #66bb6a; text-decoration: none; margin: 0 10px; }
  .divider { height: 1px; background: linear-gradient(90deg, transparent, #c8e6c9, transparent); margin: 30px 0; }
`;

const getEmailHeader = (headline, plantName) => `
  <div class="header">
    <div class="logo-section">
      <img src="cid:logo" alt="Bleaf Logo" class="logo-img" />
      <p class="tagline">Nature Knows the Way - Just Bleaf.</p>
    </div>
    <h1 style="margin: 0; font-size: 26px; color: #ffffff;">${headline}</h1>
    <p style="margin: 8px 0 0 0; color: #e8f5e9;">${plantName || 'Your plant'}</p>
  </div>
`;

const getEmailFooter = () => `
  <div class="footer">
    <div class="divider"></div>
    <p style="margin: 0 0 10px 0; color: #2e7d32; font-weight: 600;">Bleaf - Nature's Trusted Choice</p>
    <p style="margin: 10px 0;">If you have any questions, our support team is here to help.</p>
    <div class="footer-links">
      <a href="#" class="footer-link">Contact Support</a> |
      <a href="#" class="footer-link">Visit Dashboard</a>
    </div>
    <p style="margin-top: 20px; font-size: 12px;">This alert was generated by the intelligent plant care dashboard.</p>
  </div>
`;

const addNotification = async ({ userId, type, title, message, relatedEntityType = 'plant', relatedEntityId = null }) => {
  if (!userId) return null;

  const { data, error } = await supabase
    .from('notifications')
    .insert([
      {
        user_id: userId,
        type,
        title,
        message,
        related_entity_type: relatedEntityType,
        related_entity_id: relatedEntityId,
        is_read: false
      }
    ])
    .select()
    .single();

  if (error) {
    throw error;
  }

  return data;
};

const sendEmail = async ({ to, subject, headline, message, actions = [], plantName }) => {
  if (!transporter || !to) {
    return false;
  }

  const mailOptions = {
    from: process.env.EMAIL_USER,
    to,
    subject,
    html: `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <style>${emailStyles}</style>
        </head>
        <body>
          <div class="email-wrapper">
            <div class="email-container">
              ${getEmailHeader(headline, plantName)}
              <div class="content">
                <h2 class="title">Plant Care Update</h2>
                <p class="message">${message}</p>
                ${actions.length ? `
                  <div class="panel">
                    <h3>Recommended actions</h3>
                    <div>${actions.map((action) => `<span class="pill">${action}</span>`).join('')}</div>
                  </div>
                ` : ''}
              </div>
              ${getEmailFooter()}
            </div>
          </div>
        </body>
      </html>
    `,
    attachments: [{
      filename: 'logo.png',
      path: './assets/logo.png',
      cid: 'logo'
    }]
  };

  await transporter.sendMail(mailOptions);
  return true;
};

const notifyPlantEvent = async ({ userId, email, type, title, message, relatedEntityId = null, headline, actions = [], plantName }) => {
  const notification = await addNotification({
    userId,
    type,
    title,
    message,
    relatedEntityId
  });

  await sendEmail({
    to: email,
    subject: title,
    headline: headline || title,
    message,
    actions,
    plantName
  });

  return notification;
};

module.exports = {
  notifyPlantEvent,
  addNotification,
  sendEmail
};